name: Tests sur release-main


on: 
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest --cov
        python -m pytest --cov-report xml:pytest-coverage.xml
    - name: Pytest Coverage Comment
      uses: MishaKav/pytest-coverage-comment@v1.1.25
      with:
        github-token: ${{ github.token }}
        pytest-coverage-path: ./pytest-coverage.xml
        # coverage-path-prefix:
        title: Coverage Report
        badge-title: Coverage
        hide-badge: false
        hide-report: false
        hide-comment: false
        report-only-changed-files: false
        # junitxml-path: 
        # junitxml-title:
        create-new-comment: false
        default-branch: release-main
        # multiple-files:
